import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'


const post = [
  {title: 'Build an python app ', excerpt : 'Setup a a vm'},
  {title: 'docker as a pro  ', excerpt : 'Setup a a vm'}
]


export default function Home() {
  return (
    <div className=' container mx-auto px-10 mb-8 '>
      <Head>
        <title>YourDevopsDoor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <div className="grid grid-cols-1 lg:grid-cols-12 gap-12">

{post.map((post,index) => 
(   
<div className=" ">

  {post.title}
  {post.excerpt}
</div>

)
)}

     </div>
    </div>
  )
}
