import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { PostCard, Categories, PostWidget,Navbar } from '../Components/'
import { getPosts } from '../services'

// const post = [
//   { title: 'Build an python app ', excerpt: 'Setup a a vm' },
//   { title: 'docker as a pro  ', excerpt: 'Setup a a vm' },

// ]


export default function Home({posts}) {
  
  console.log(posts);
  return (
    <div className=' container mx-auto px-10 mb-8 '>
      <Head>
        <title>YourDevopsDoor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex space-x-6">
{/* On map a travers Les post */}
        <div className=" text-4xl  text-bold text-white">
          <div className=" bg-slate-100  rounded-xl py-6 sm:py-12 px-4 xl:px-0"> 
          <div className="lg:flex  flex-col  items-center  space-y-24 justify-center w-full"> 
        {posts.map((post) => <PostCard post={post.node} key={post.title} />)}
          </div>
          </div>
          </div>
<div className="lg:col-span-4 col-span-1 text-2xl  text-bold text-white">
  <div className="lg:sticky relative space-y-10 top-8">
    <PostWidget/>
    <Categories/>
  </div>
</div>
      </div>
    </div>
  )
}

export async function getStaticProps(){
  const posts = (await getPosts()) || [];

  return {
    props: {posts}
  }
}